### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by daodaoawaker** [AlextheEngineer/Ego2Hands#2]
Hi, The download link of datasets and pretrained-model is unavailable. Could you check these agian ? Thanks

**Comment by AlextheEngineer** [comment]
The server might have been temporarily down, can you try again? The links work for me

**Comment by daodaoawaker** [comment]
I'm so sad, I have tried  several times, but it's stilling not working.

**Comment by AlextheEngineer** [comment]
What's the error? Is the website not working or does the website work but you are not able to download? The 4 files for training are about 20G each, do you have enough space?

**Comment by daodaoawaker** [comment]
It seems the website is not working, my disk space is enough. When I click the download link，there is only one empty website jump...

**Comment by AlextheEngineer** [comment]
So the BYU box webiste does open and you see a download button right? But clicking the button doesn't lead to the actual downloading?

**Comment by daodaoawaker** [comment]
There only a BYU box website open, no button. Can you supply a Googledrive link ? I‘ll appreciate

**Comment by AlextheEngineer** [comment]
I don't have enough space for google drive and my school provides unlimited storage. Where are you downloading from?

**Comment by daodaoawaker** [comment]
I have download these datasets by other's help. Thank you all the same.

**Comment by AlextheEngineer** [comment]
Sorry for the inconvenience. Hope the dataset helps!
