### ISSUE TITLE
Error when adapting a pretrained model on custom sequence

### ISSUE THREAD

**Issue by ch1474** [AlextheEngineer/Ego2Hands#3]
Hi!

I think I have followed the instructions correctly for adapting the pretrained model, but I am getting this error.  I have managed to get it working without adapting the model. 

![image](https://user-images.githubusercontent.com/18485021/109554118-bd6e3c00-7acb-11eb-8ba3-abee80a83bad.png)

[error.txt](https://github.com/AlextheEngineer/Ego2Hands/files/6064232/error.txt)

Thanks, 

Cam

**Comment by AlextheEngineer** [comment]
Hi, "#hand imgs: 0" indicates that it didn't find any hand images in the directory you have specified for training. Have you set the "dataset_train_dir" in the config file to the dataset's train directory ("data/Ego2Hands/train")? If so, have you downloaded the dataset so that the train directory has 22 subjects' hand data?

**Comment by ch1474** [comment]
Hi Alex, 

Thanks for your quick response, I've downloaded everything and put them in the correct directories. I am getting a new error however (attached). It seems that no background images are being found now. Not sure if this is for the web backgrounds or my custome one, never the less I've double checked that the're in the right place. Will have another look tomorrow morning. 

Thanks for sharing your work, i'm eager to get it working!

Thanks, 

Cam

[error2.txt](https://github.com/AlextheEngineer/Ego2Hands/files/6065202/error2.txt)

Edit: 

Thought i'd clarify the background folders

![image](https://user-images.githubusercontent.com/18485021/109576916-96743200-7aec-11eb-9d2f-c793a0c5b742.png)

![image](https://user-images.githubusercontent.com/18485021/109576937-9e33d680-7aec-11eb-854a-369803780efb.png)

**Comment by ch1474** [comment]
Solved, named them '.jpeg' instead of '.jpg'

**Comment by AlextheEngineer** [comment]
Sorry for missing that, it can be easily fixed if you modify line 137 of this file: data_loaders/Ego2Hands.py. I'll make the change also.
