### ISSUE TITLE
Background_web_download_failed

### ISSUE THREAD

**Issue by elfpattern** [AlextheEngineer/Ego2Hands#4]
When I download the backgrounds, It failed halfway through the download.
![image](https://user-images.githubusercontent.com/26590396/123050623-79fd5c00-d433-11eb-9ebb-92a14dc0d744.png)

**Comment by AlextheEngineer** [comment]
Hi, I'm able to download the background file, do you have a stable internet connection? The file is about 8GB.

**Comment by elfpattern** [comment]
Hi，&nbsp; Thx for reply, It is really a internet connection question. I downloaded it .




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月23日(星期三) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AlextheEngineer/Ego2Hands] Background_web_download_failed (#4)





 
Hi, I'm able to download the background file, do you have a stable internet connection?

**Comment by AlextheEngineer** [comment]
Good to hear! Thanks
