### ISSUE TITLE
Weights for the segmentation models compared in the paper

### ISSUE THREAD

**Issue by NeelayS** [AlextheEngineer/Ego2Hands#5]
Hi @AlextheEngineer, thanks for making the dataset and your code available! I found Table 3 in the paper comparing different models on hand segmentation performance especially insightful. I was wondering whether you could possibly share the trained/adapted weights for the models present in that table with me.
Thanks!

**Comment by AlextheEngineer** [comment]
Thanks for your interests! I used implementations from https://github.com/kcyu2014/recurrent-unet and simply modified the output channel (see the provided CSM for an example.) You can add models to my pipeline and train/test different architectures. Note larger architectures rely on pretrained backbone for better performance.
