### ISSUE TITLE
Is it possible that google drive version of dataset can be provided for download?

### ISSUE THREAD

**Issue by MichiganLu** [AlextheEngineer/Ego2Hands#6]
Hi,

Firstly awesome work. I have read your paper and find it really intriguing and promising to use your dataset to train on some recent SOTA segmentation networks for my project. However, I tried several times to download from the box link but failed. After a couple of hours, the download would die signifiying that download link became invalid. Then I had to redownload the entire dataset from the beginning. If possible, will you be able to provide the dataset with a more stable share drive, like Google drive?

Thanks.

**Comment by AlextheEngineer** [comment]
Thanks for your interest! I don't have Google drive space large enough for these datasets. Would it be helpful if I divide the dataset into smaller chunks (e.g. 1 subject per download link)?

**Comment by MichiganLu** [comment]
> 

Sure, that is definitely gonna help. I would really appreciate that:)

**Comment by AlextheEngineer** [comment]
I've updated the download links, let me know if you have additional questions!
